# Generated by Django 4.2.1 on 2023-05-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
